//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mairegger.Printing.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class l10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal l10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mairegger.Printing.Properties.l10n", typeof(l10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is no valid column dimension..
        /// </summary>
        public static string ColumnDimensionAttribute_ColumnDimensionAttribute__0__is_no_valid_column_dimension {
            get {
                return ResourceManager.GetString("ColumnDimensionAttribute_ColumnDimensionAttribute__0__is_no_valid_column_dimensio" +
                        "n", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between 0 and 1..
        /// </summary>
        public static string ColumnDimensionAttribute_ColumnDimensionAttribute_The_value_must_be_between_0_and_1_ {
            get {
                return ResourceManager.GetString("ColumnDimensionAttribute_ColumnDimensionAttribute_The_value_must_be_between_0_and" +
                        "_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be lower or equal than {1}..
        /// </summary>
        public static string PageRange_PageRange__0__must_be_lower_or_equal_than__1_ {
            get {
                return ResourceManager.GetString("PageRange_PageRange__0__must_be_lower_or_equal_than__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string PageRange_Parse_Invalid_format {
            get {
                return ResourceManager.GetString("PageRange_Parse_Invalid_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must return a value for &quot;Get{1}()&quot; if &quot;{2}&quot; is set..
        /// </summary>
        public static string PrintDimension_GetHeightFor__0__must_return_a_value_for__Get_1_____if___2___is_set_ {
            get {
                return ResourceManager.GetString("PrintDimension_GetHeightFor__0__must_return_a_value_for__Get_1_____if___2___is_se" +
                        "t_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be a positive number or null..
        /// </summary>
        public static string PrintDimension_SetHeightValue_Must_be_a_positive_number_or_null {
            get {
                return ResourceManager.GetString("PrintDimension_SetHeightValue_Must_be_a_positive_number_or_null", resourceCulture);
            }
        }
    }
}
