<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(NetCoreWpfCurrent);$(NetCoreWpfPrevious);$(NetCoreWpfMinimum)</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <!-- this is only because of NetCoreAppMinimum is needed below in references -->
    <NetCoreAppMinimum Condition="'$(NetCoreAppMinimum)' == ''">$(NetCoreAppPrevious)</NetCoreAppMinimum>
    <NetCoreAppMinimum Condition="'$(NetCoreAppMinimum)' == ''">$(NetCoreAppCurrent)</NetCoreAppMinimum>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Testing.Platform" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Xunit.StaFact" />
    <PackageReference Include="xunit.v3.mtp-v2" />

    <Reference Include="System.Printing" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', '$(NetCoreAppMinimum)'))"  />
    <Reference Include="ReachFramework" Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', '$(NetCoreAppMinimum)'))"  />
  </ItemGroup>

  <PropertyGroup>
    <!--otherwise no code coverage files are generated -->
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mairegger.Printing\Mairegger.Printing.csproj" />
  </ItemGroup>
</Project>
