name: 'Compile, test'
inputs:
  buildConfiguration:
    required: true
  workingDirectory:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/setup-dotnet@v2
    with:
      dotnet-version: |
        3.1.x
        6.0.x
        7.0.x
      
  - uses: dotnet/nbgv@master
    id: nbgv

  - name: Cache SonarCloud packages
    uses: actions/cache@v1
    with:
      path: ~\sonar\cache
      key: ${{ runner.os }}-sonar
      restore-keys: ${{ runner.os }}-sonar

  - name: Install SonarCloud scanner
    shell: pwsh
    run: dotnet tool update dotnet-sonarscanner -g

  - name: Install reportgenerator
    shell: pwsh
    run: dotnet tool update dotnet-reportgenerator-globaltool -g

  - name: Restore dependencies
    shell: pwsh
    run: dotnet restore
    working-directory: ${{ inputs.workingDirectory }}

  - name: Sonarscanner begin
    shell: pwsh
    run: dotnet sonarscanner begin /k:"mairegger.printing" /o:"mairegger" /d:sonar.login="${{ env.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.coverageReportPaths="sonarqubecoverage\SonarQube.xml"
    working-directory: ${{ inputs.workingDirectory }}

  - name: Build
    shell: pwsh
    run: dotnet build --configuration ${{ inputs.buildConfiguration }} --no-restore
    working-directory: ${{ inputs.workingDirectory }}

  - name: Test
    shell: pwsh
    run: dotnet test --configuration ${{ inputs.buildConfiguration }} --no-build --collect:"XPlat Code Coverage"
    working-directory: ${{ inputs.workingDirectory }}

  - name: Set up JDK 11
    uses: actions/setup-java@v1
    with:
      java-version: 1.11
      
  - name: Sonarscanner end
    shell: pwsh
    run: |
      reportgenerator "-reports:*\TestResults\*\coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube"
      dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"
    working-directory: ${{ inputs.workingDirectory }}