<Project>
  <PropertyGroup>
    <!-- .NET Framework Support Dates https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework -->
    <!-- .NET Support Dates https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core -->
    <CurrentNetVersion>10.0.11</CurrentNetVersion>
    <PreviousNetVersion>9.0.19</PreviousNetVersion>
    <!-- note: when upgrading MinimumNetVersion ensure there is no NET(__version__)_0_OR_GREATER where __version__ is lower than the new MinimumNetVersion -->
    <MinimumNetVersion>8.0.30</MinimumNetVersion>
    <WindowsSdkVersion>10.0.19041.0</WindowsSdkVersion>

    <!-- note: when removing NETFRAMEWORK ensure there is no NETFRAMEWORK prepocessor symbol in code  -->
    <NetFrameworkMinimum>net462</NetFrameworkMinimum>
  </PropertyGroup>

  <PropertyGroup Label="Minimum versions">
    <MinWpfAnalyzersVersion>4.1.1</MinWpfAnalyzersVersion>

    <MinBogusVersion>35.6.5</MinBogusVersion>
    <MinTUnitVersion>1.65.0</MinTUnitVersion>
    <MinMicrosoftNETTestSdkVersion>18.9.0</MinMicrosoftNETTestSdkVersion>
    <MinMicrosoftTestingExtensionsCodeCoverageVersion>18.10.0</MinMicrosoftTestingExtensionsCodeCoverageVersion>
    <MinMicrosoftTestingPlatformVersion>2.3.3</MinMicrosoftTestingPlatformVersion>
  </PropertyGroup>

  <PropertyGroup>
    <NerdbankGitVersioningVersion>3.10.94</NerdbankGitVersioningVersion>
    <WpfAnalyzersVersion>$(MinWpfAnalyzersVersion)</WpfAnalyzersVersion>

    <!--Testing -->
    <BogusVersion>$(MinBogusVersion)</BogusVersion>
    <TUnitVersion>$(MinTUnitVersion)</TUnitVersion>
    <MicrosoftNETTestSdkVersion>$(MinMicrosoftNETTestSdkVersion)</MicrosoftNETTestSdkVersion>
    <MicrosoftTestingExtensionsCodeCoverageVersion>$(MinMicrosoftTestingExtensionsCodeCoverageVersion)</MicrosoftTestingExtensionsCodeCoverageVersion>
    <MicrosoftTestingPlatformVersion>$(MinMicrosoftTestingPlatformVersion)</MicrosoftTestingPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Label="Allow to overwrite versions from base Versions.props">
    <ParentDirectoryVersionsPropsPath>$([MSBuild]::GetPathOfFileAbove('Versions.props', '$(MSBuildThisFileDirectory)../'))</ParentDirectoryVersionsPropsPath>
  </PropertyGroup>
  <Import Project="$(ParentDirectoryVersionsPropsPath)" Condition="'$(ParentDirectoryVersionsPropsPath)' != '' and Exists($(ParentDirectoryVersionsPropsPath))" />

  <Import Project="$(MSBuildThisFileName).targets" />

</Project>
