name: Build
on:
  push:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - uses: dotnet/nbgv@master
      id: nbgv
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 3.1.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 5.0.x
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
      working-directory: src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: src
    - name: Test
      run: dotnet test --configuration Release --no-build
      working-directory: src
