name: Build
on:
  push:

env:
  buildConfiguration: 'Release'
  workingDirectory: 'src'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ./.github/actions/build-and-test
      with:
        buildConfiguration: ${{ env.buildConfiguration }}
        workingDirectory: ${{ env.workingDirectory }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}