name: Publish
on:
  push:
    tags:
      - 'v*.*.*'

env:
  buildConfiguration: 'Release'
  workingDirectory: 'src'

jobs:
  deploy:
    runs-on: windows-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/build-and-test
        id: build-and-test
        with:
          buildConfiguration: ${{ env.buildConfiguration }}
          workingDirectory: ${{ env.workingDirectory }}

      - name: Pack
        run: dotnet pack --configuration Release --no-build --output artifacts
        working-directory: src

      - name: Push with dotnet
        run: dotnet nuget push artifacts\*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: src
